export const courses = [
    {
      id: 23,
      course_id: 8904,
      course_overview_provider: "vineo",
      course_overview_url: "www.vimeo.com",
      course_price: "25",
      course_title: "Blood Pressure",
      description:
        "<p>The Basic Life Support (BLS) program is for participants to gain or improve knowledge and skill proficiency in high-quality CPR skills and teamwork for the adult, child, and infant.</p>",
      discounted_price: "5%",
      faq: "Blood",
      has_discount: true,
      is_free_course: false,
      meta_description: "LinkedIn",
      meta_keywords: "meta facebook",
      requirements: "Pressure",
      selected_language: "English",
      selected_programming_language: "health",
      selected_programming_level: "Beginner",
      short_description: "Blood Pressure",
      created_at: "2024-07-15T13:03:31.933Z",
      created_by: "4",
      lesson: "9",
      section: "3",
      status: "active",
      thumbnail: null,
      updated_at: "2024-07-17T17:00:03.649Z",
    },
    {
      id: 25,
      course_id: 6771,
      course_overview_provider: "vineo",
      course_overview_url: "www.vimeo.com",
      course_price: "75",
      course_title: "Basic Nutrition",
      description:
        "<p>The Basic Life Support (BLS) program is for participants to gain or improve knowledge and skill proficiency in high-quality CPR skills and teamwork for the adult, child, and infant.</p>",
      discounted_price: "5%",
      faq: "Basic Question",
      has_discount: true,
      is_free_course: false,
      meta_description: "FB",
      meta_keywords: "Facebook",
      requirements: "Basic Nutrition",
      selected_language: "English",
      selected_programming_language: "health",
      selected_programming_level: "Intermediate",
      short_description: "Basic Life Support (BLS)",
      created_at: "2024-07-15T16:45:52.877Z",
      created_by: "4",
      lesson: "10",
      section: "3",
      status: "active",
      thumbnail: null,
      updated_at: "2024-07-17T17:00:03.649Z",
    },
    {
      id: 26,
      course_id: 6841,
      course_overview_provider: "vineo",
      course_overview_url: "www.vimeo.com",
      course_price: "70",
      course_title: "CABS",
      description:
        "<p>The Child and Babysitting Safety (CABS) program gives teenagers and young adults everything they need to know for safe and successful babysitting. From getting started with a business, to working with parents and children, to key safety, caregiving, and first aid tips- you will have a blast! Course Topics Include Babysitting as a business Safety and injury prevention guidelines and best practices Leadership strategies to build confidence when responding to conflict Tips on age-appropriate play How to build rapport and stay engaged with children Basic caregiving skills such as feeding, burping, diapering, and safe sleep practices Basic first aid for common incidents</span></p>",
      discounted_price: "10%",
      faq: "How can we make sure that baby is in safe hand?",
      has_discount: true,
      is_free_course: false,
      meta_description: "Linked IN",
      meta_keywords: "Baby facebook",
      requirements:
        "Always put your baby or child in an approved restraint when travelling by car. Always use the five-point safety harness in your highchair, stroller or pram.",
      selected_language: "English",
      selected_programming_language: "social_issues",
      selected_programming_level: "Intermediate",
      short_description: "Child and Babysitting Safety Course (CABS) Bundle",
      created_at: "2024-07-17T16:15:48.577Z",
      created_by: "4",
      lesson: "4",
      section: "3",
      status: "active",
      thumbnail: null,
      updated_at: "2024-07-17T17:00:03.649Z",
    },
    {
      id: 27,
      course_id: 2576,
      course_overview_provider: "html5",
      course_overview_url: "www.Html5.com",
      course_price: "60",
      course_title: "First Aid",
      description:
        "<p>Course Content for First AidUsing of Personal Protective Equipment (PPE), shock, bleeding, diabetes, asthma, anaphylaxis, seizures, internal and external injuries, burns, poisoning, bites and stings, heat emergencies and cold emergencies.&nbsp;Duration:&nbsp;Approximately 2 hoursThis certification is valid for 2 years.Audience: Anyone needing a certification that specifically states “First Aid\"&nbsp;&nbsp;WE CAN COME TO YOU!Call our office if you have a large group and would like an instructor to come to your facility.</span></p>",
      discounted_price: "20%",
      faq: "Some Questions",
      has_discount: true,
      is_free_course: false,
      meta_description: " +++++",
      meta_keywords: "First Aid",
      requirements: "the questions",
      selected_language: "English",
      selected_programming_language: "health",
      selected_programming_level: "Intermediate",
      short_description: "Course Content for First Aid Using of PPE",
      created_at: "2024-07-17T17:19:52.247Z",
      created_by: "4",
      lesson: "8",
      section: "2",
      status: "active",
      thumbnail: null,
      updated_at: "2024-07-17T17:19:52.247Z",
    },
    {
      id: 28,
      course_id: 7707,
      course_overview_provider: "html5",
      course_overview_url: "www.Html5.com",
      course_price: "80",
      course_title: "Blood Oxygen",
      description:
        "<p>A normal level of oxygen is usually&nbsp;<span style=\"color: rgb(4, 12, 40); background-color: rgb(211, 227, 253);\">95% or higher</span>. Some people with chronic lung disease or sleep apnea can have normal levels around 90%</span></p>",
      discounted_price: "",
      faq: "On related to Health",
      has_discount: false,
      is_free_course: false,
      meta_description: "meta",
      meta_keywords: "facebook",
      requirements: "testing",
      selected_language: "English",
      selected_programming_language: "social_issues",
      selected_programming_level: "Intermediate",
      short_description: "Oxygen level checker",
      created_at: "2024-07-17T17:26:36.698Z",
      created_by: "4",
      lesson: "8",
      section: "5",
      status: "active",
      thumbnail: null,
      updated_at: "2024-07-17T17:26:36.698Z",
    },
    {
      id: 29,
      course_id: 6203,
      course_overview_provider: "youtube",
      course_overview_url: "456",
      course_price: "50",
      course_title: "CPR",
      description:
        "<p>(CPR) is an emergency treatment that's done when someone's breathing or heartbeat has stopped.</p>",
      discounted_price: "",
      faq: "CPR",
      has_discount: false,
      is_free_course: false,
      meta_description: "",
      meta_keywords: "meta facebook",
      requirements: "45",
      selected_language: "English",
      selected_programming_language: "social_issues",
      selected_programming_level: "Beginner",
      short_description: "Cardiopulmonary resuscitation (CPR)",
      created_at: "2024-07-17T17:35:05.633Z",
      created_by: "4",
      lesson: "8",
      section: "5",
      status: "active",
      thumbnail: null,
      updated_at: "2024-07-17T17:35:05.633Z",
    },
    {
      id: 40,
      course_id: 64017,
      course_overview_provider: null,
      course_overview_url: "",
      course_price: "",
      course_title: "Test Course",
      description: "",
      discounted_price: "",
      faq: "",
      has_discount: false,
      is_free_course: true,
      meta_description: "",
      meta_keywords: "",
      requirements: "",
      selected_language: null,
      selected_programming_language: "health",
      selected_programming_level: null,
      short_description: "Test Course",
      created_at: "2024-08-20T16:45:20.237Z",
      created_by: "14",
      lesson: "",
      section: "",
      status: "active",
      thumbnail: "",
      updated_at: "2024-08-20T16:45:20.237Z",
    },
  ];
  